import React from 'react';
import { 
    mdiMusicNoteEighth,
    mdiWrench,
    mdiCake,
    mdiFlower,
    mdiPizza,
    mdiTrainCar,
    mdiBabyCarriage,
    mdiLaptop,
    mdiHome,
    mdiBed,
    mdiEmail,
    mdiPalette,
    mdiFormatPaint,
    mdiSilverwareForkKnife,
    mdiSchool,
    mdiCart,
    mdiGamepadSquare,
    mdiHockeySticks,
    mdiTerrain,
    mdiBike,

} from '@mdi/js';
import {
    Audiotrack,
    Build,
    Cake,
    ChildFriendly,
    Commute,
    Computer,
    Home,
    Hotel,
    LocalFlorist,
    LocalPizza,
    Mail,
    FormatPaint,
    Palette,
    Restaurant,
    School,
    ShoppingCart,
    VideogameAsset,
    Terrain,
    DirectionsBike,
    SportsHockey,
} from '@material-ui/icons';

export const serviceIconMap = {
    audiotrack: { component: <Audiotrack />, path: mdiMusicNoteEighth },
    build: { component: <Build />, path: mdiWrench },
    cake: { component: <Cake />, path: mdiCake },
    childfriendly: { component: <ChildFriendly />, path: mdiBabyCarriage },
    commute: { component: <Commute />, path: mdiTrainCar },
    computer: { component: <Computer />, path: mdiLaptop },
    home: { component: <Home />, path: mdiHome },
    hotel: { component: <Hotel />, path: mdiBed },
    localflorist: { component: <LocalFlorist />, path: mdiFlower },
    localpizza: { component: <LocalPizza />, path: mdiPizza },
    mail: { component: <Mail />, path: mdiEmail },
    formatPaint: { component: <FormatPaint />, path: mdiFormatPaint },
    palette: { component: <Palette />, path: mdiPalette },
    restaurant: { component: <Restaurant />, path: mdiSilverwareForkKnife },
    school: { component: <School />, path: mdiSchool },
    shoppingcart: { component: <ShoppingCart />, path: mdiCart },
    videogameasset: { component: <VideogameAsset />, path: mdiGamepadSquare },
    sportshockey: { component: <SportsHockey />, path: mdiHockeySticks },
    terrain: { component: <Terrain />, path: mdiTerrain },
    directionsbike: { component: <DirectionsBike />, path: mdiBike },
};

export default serviceIconMap;
