name: Run Tests
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    Formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Format
              run: |
                  npm ci
                  npx prettier --check "**/*.{js,md}"
    Mobile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd mobile/
                  npm ci
                  npm test
                  cd ../
    Web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd web/
                  npm ci
                  npm test
                  cd ../
    Server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd server/
                  npm ci
                  npm test
                  cd ../
