name: CI
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Mobile Test
              run: |
                  cd mobile/
                  npm ci
                  npm test
                  cd ../
            - name: Web Test
              run: |
                  cd web/
                  npm ci
                  npm test
                  cd ../
            - name: Server Test
              run: |
                  cd server/
                  npm ci
                  npm test
                  cd ../
