name: Run All Tests
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    Mobile-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd mobile/
                  npm ci
                  npm test
                  cd ../
    Web-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd web/
                  npm ci
                  npm test
                  cd ../
    Server-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Run Tests
              run: |
                  cd server/
                  npm ci
                  npm test
                  cd ../
