name: format
on:
    pull_request:
        branches: [main]
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v2.1.4
              with:
                  node-version: '12.x'
            - name: Format
              run: |
                  npm ci
                  npm prettier --list-different **/*.{js,md}
