name: Check Formatting
on:
    pull_request:
        branches: [main]
jobs:
    format-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Format
              run: |
                  npm ci
                  npx prettier --check "**/*.{js,md}"
